export enum Subjects {
    UserCreated = "user:created",
    UserActivated = "user:activated",
    UserUpdated = "user:updated",
    ProfileCreated = "profile:created",
    ProfileUpdated = "profile:updated",
    ProfileDeleted = "profile:deleted",
    NewsItemCreated = "newsitem:created",
    NewsItemUpdated = "newsitem:updated",
    NewsItemDeleted = "newsitem:deleted",
    FetchAllNewsItems = "newsitem:fetchall",
    BlogPostCreated = "blogpost:created",
    BlogPostUpdated = "blogpost:updated",
    BlogPostDeleted = "blogpost:deleted",
    GroupCreated = "group:created",
    GroupUpdated = "group:updated",
    GroupDeleted = "group:deleted",
    TeamCreated = "team:created",
    TeamUpdated = "team:updated",
    TeamDeleted = "team:deleted"
}
